In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
%ls

drive/  sample_data/


In [3]:
%cd 'drive'

/content/drive


In [4]:
%cd 'MyDrive'

/content/drive/MyDrive


In [5]:
%ls


 05db7df4f31840f0a873d6ea14dcc28d.pdf
'119153746 (1).pdf'
 119153746_1.pdf
'119153746 (2).pdf'
 119153746.pdf
'190929198   Deeptej More    94.pdf'
'190929198_Deeptej More_Case Study.gdoc'
'20191122_001012 (1).jpg'
'20191122_001012 (2).jpg'
 20191122_001012.jpg
'20191122_001023 (1).jpg'
'20191122_001023 (2).jpg'
 20191122_001023.jpg
'20191122_001034 (1).jpg'
'20191122_001034 (2).jpg'
 20191122_001034.jpg
'20191122_001050 (1).jpg'
'20191122_001050 (2).jpg'
 20191122_001050.jpg
'20191122_001107 (1).jpg'
'20191122_001107 (2).jpg'
 20191122_001107.jpg
'20191122_001121 (1).jpg'
'20191122_001121 (2).jpg'
 20191122_001121.jpg
'20191122_001135 (1).jpg'
'20191122_001135 (2).jpg'
 20191122_001135.jpg
'20191122_001208 (1).jpg'
'20191122_001208 (2).jpg'
 20191122_001208.jpg
'20191122_001219 (1).jpg'
'20191122_001219 (2).jpg'
 20191122_001219.jpg
'20191122_001224 (1).jpg'
'20191122_001224 (2).jpg'
 20191122_001224.jpg
'20191122_001237 (1).jpg'
'20191122_001237 (2).jpg'
 20191122_001237.jpg
'20191122

In [6]:
%cd custom_photos/

/content/drive/MyDrive/custom_photos


In [7]:
%ls

'American Crow'/                'Blue Jay'/
'American Goldfinch (Female)'/  'Common Grackle'/
'American Goldfinch (Male)'/    'House Sparrow (Female)'/
'American Robin (Adult)'/       'House Sparrow (Male)'/
'American Robin (Juvenile)'/    'House Wren'/
 BirdDetectionDeep-2.h5         'Mourning Dove'/
 BirdDetectionDeep-2.json       'Northern Cardinal (Adult Male)'/
 BirdDetectionDeep-3-best.h5    'Northern Cardinal (Female)'/
 BirdDetectionDeep-3-best.json  'Red-tailed Hawk (Dark morph)'/
 BirdDetectionDeep.h5           'Red-tailed Hawk (Light morph immature)'/
 BirdDetectionDeep.json         'Tufted Titmouse'/


In [8]:
import os
import cv2
import glob

list_images = {}
curr_dir =  os.getcwd()
list_dir = os.listdir(curr_dir)
print(list_dir)


# for folder in list_dir:
#     print(folder)
image_array = []
for folder in list_dir:
    for img in glob.glob(str(folder)+"/*.jpg"):
      print(img)
      image = cv2.imread(img)
      image_array.append(image)
      if image is not None:
        list_images[img]=folder

['House Wren', 'Red-tailed Hawk (Dark morph)', 'House Sparrow (Female)', 'American Robin (Adult)', 'Northern Cardinal (Adult Male)', 'American Goldfinch (Male)', 'American Goldfinch (Female)', 'American Robin (Juvenile)', 'House Sparrow (Male)', 'American Crow', 'Tufted Titmouse', 'Red-tailed Hawk (Light morph immature)', 'Blue Jay', 'Common Grackle', 'Mourning Dove', 'Northern Cardinal (Female)', 'BirdDetectionDeep.json', 'BirdDetectionDeep.h5', 'BirdDetectionDeep-3-best.json', 'BirdDetectionDeep-3-best.h5', 'BirdDetectionDeep-2.json', 'BirdDetectionDeep-2.h5']
House Wren/65e0b59279794997bea5f8a8cb220467.jpg
House Wren/ff8dbc12727c4df2b19efd39f5df4c6e.jpg
House Wren/e89159a1738d47248465d34e99bff03e.jpg
House Wren/59ca4cab637e41e7b8707f003a3cc219.jpg
House Wren/75dc62b82671438fab15431c11269919.jpg
House Wren/a989ffa20374414590528589e8b393ac.jpg
House Wren/5cce7adab6734dc4b8310e507e357876.jpg
House Wren/7769d03d79374188bfb056c9800d7bf6.jpg
House Wren/e9aba577f0ee432ba28c3db942d5b680.jpg

In [9]:
print(list_images)

{'House Wren/65e0b59279794997bea5f8a8cb220467.jpg': 'House Wren', 'House Wren/ff8dbc12727c4df2b19efd39f5df4c6e.jpg': 'House Wren', 'House Wren/e89159a1738d47248465d34e99bff03e.jpg': 'House Wren', 'House Wren/59ca4cab637e41e7b8707f003a3cc219.jpg': 'House Wren', 'House Wren/75dc62b82671438fab15431c11269919.jpg': 'House Wren', 'House Wren/a989ffa20374414590528589e8b393ac.jpg': 'House Wren', 'House Wren/5cce7adab6734dc4b8310e507e357876.jpg': 'House Wren', 'House Wren/7769d03d79374188bfb056c9800d7bf6.jpg': 'House Wren', 'House Wren/e9aba577f0ee432ba28c3db942d5b680.jpg': 'House Wren', 'House Wren/92caf06dac89478ba8761ec64536d824.jpg': 'House Wren', 'House Wren/15424421bdef4ca3a4c2c1e08f6697d7.jpg': 'House Wren', 'House Wren/db2601f0175a42b2a94e8dead0c7d049.jpg': 'House Wren', 'House Wren/e1cc648889814640bfeabcb212b451a1.jpg': 'House Wren', 'House Wren/d02b31c019224be28f8632410db39455.jpg': 'House Wren', 'House Wren/87d0fad5d98540719b6db90ee2236e93.jpg': 'House Wren', 'House Wren/bba8c67a789d

In [10]:
print(image_array[0].shape)

(1024, 1024, 3)


In [11]:
image_array2 = []
for image in image_array:
  image2 = cv2.resize(image,(150,150))
  image_array2.append(image2)

In [12]:
print(image_array2[0].shape)

(150, 150, 3)


In [13]:
labels = []
for folder in list_dir:
    for img in glob.glob(str(folder)+"/*.jpg"):
      labels.append(str(folder))

In [14]:
print(labels)

['House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'House Wren', 'Hous

In [15]:
def unique_labels_words(labels):
  uniq_labels_words=[]
  for i in labels:
    if i in uniq_labels_words:
      continue
    else:
      uniq_labels_words.append(i)
  print(uniq_labels_words)
unique_labels_words(labels)

['House Wren', 'Red-tailed Hawk (Dark morph)', 'House Sparrow (Female)', 'American Robin (Adult)', 'Northern Cardinal (Adult Male)', 'American Goldfinch (Male)', 'American Goldfinch (Female)', 'American Robin (Juvenile)', 'House Sparrow (Male)', 'American Crow', 'Tufted Titmouse', 'Red-tailed Hawk (Light morph immature)', 'Blue Jay', 'Common Grackle', 'Mourning Dove', 'Northern Cardinal (Female)']


In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
labels = le.fit_transform(labels)

In [17]:
def unique_labels_digits(labels):
  uniq_labels_digits=[]
  for i in labels:
    if i in uniq_labels_digits:
      continue
    else:
      uniq_labels_digits.append(i)
  print(uniq_labels_digits)
unique_labels_digits(labels)

[9, 13, 7, 3, 11, 2, 1, 4, 8, 0, 15, 14, 5, 6, 10, 12]


In [18]:
import tensorflow 
df = tensorflow.keras.utils.to_categorical(labels,num_classes=16,dtype='float32')

In [19]:
print(df)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [20]:
# cv2.imshow(str(labels[3]),image_array2[3])

In [21]:
import numpy as np
x_train = np.array(image_array2)
y_train = df

In [22]:
print("x_dims:",x_train.shape)
print("y_dims:",y_train.shape)

x_dims: (1789, 150, 150, 3)
y_dims: (1789, 16)


In [23]:
x_train.reshape(-1,150,150,3)
print(x_train.shape)

(1789, 150, 150, 3)


In [24]:
print(x_train[0].shape)

(150, 150, 3)


In [25]:
# import tensorflow 
# df = tensorflow.keras.utils.to_categorical(labels,num_classes=16,dtype='float32')

In [26]:
df.shape

(1789, 16)

In [39]:
from tensorflow.keras.applications.inception_v3 import InceptionV3
from tensorflow.keras.optimizers import RMSprop
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization,AveragePooling2D
from keras.losses import categorical_crossentropy
from keras.optimizers import Adam
from keras.regularizers import l2,l1_l2
from keras.utils import np_utils

In [40]:
pre_trained_model = InceptionV3(input_shape=(150,150,3),include_top=False, weights = 'imagenet')
for layer in pre_trained_model.layers:
  layer.trainable = False


In [47]:
x = Flatten()(pre_trained_model.output)
x = Dense(1024,activation = 'relu',kernel_regularizer = l1_l2(l1=1e-5, l2=1e-4))(x)
x = BatchNormalization()(x)
# x = Dropout(0.2)(x)
x = Dense(512,activation = 'relu')(x)
x = BatchNormalization()(x)
x = Flatten()(x)
x = Dense(128,activation='relu')(x)
x = Dense(64,activation='relu')(x)
x = Dense(16 , activation = 'softmax')(x)

In [48]:
from tensorflow.keras.models import Model
model = Model(pre_trained_model.input , x)

In [ ]:
model.summary()

In [50]:
model.compile(loss=categorical_crossentropy,optimizer=tensorflow.keras.optimizers.SGD(lr=1e-2, momentum=0.9, decay=1e-2 /10)
,metrics=['accuracy'])


In [51]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
datagen = ImageDataGenerator(rescale=1./255.,rotation_range = 40,width_shift_range =0.2 ,height_shift_range = 0.2,shear_range =0.2,zoom_range = 0.2,horizontal_flip = True,validation_split=0.2)

from sklearn.model_selection import train_test_split

val_split = 0.25
X_train, X_val, Y_train, Y_val = train_test_split(x_train, y_train, test_size=val_split, stratify = y_train)

X_train = X_train/255.
X_val = X_val/255.


# train_generator = datagen.flow(x_train,
#                                y_train,
#                                batch_size=32,
#                                seed=0,
#                                subset='training')

# valid_generator = datagen.flow(x_train,
#                                y_train,
#                                batch_size=16,
#                                seed=0,
#                             subset='validation')

In [52]:
print(X_train.shape, X_val.shape, Y_train.shape, Y_val.shape)

(1341, 150, 150, 3) (448, 150, 150, 3) (1341, 16) (448, 16)


In [37]:
# print(train_generator.n)
# print(valid_generator.n)

In [53]:
model.fit(X_train, Y_train,
          batch_size=32,
          epochs=30,
          verbose=2,
          validation_data=(X_val, Y_val),
          shuffle=False)

# STEP_SIZE_TRAIN=train_generator.n//train_generator.batch_size
# STEP_SIZE_VALID=valid_generator.n//valid_generator.batch_size

# model.fit(train_generator,
#           steps_per_epoch=32,
#           validation_data=valid_generator,
#           validation_steps=16,
#           epochs=10)

Epoch 1/30
42/42 - 4s - loss: 3.8944 - accuracy: 0.3661 - val_loss: 6.3938 - val_accuracy: 0.2991
Epoch 2/30
42/42 - 2s - loss: 2.9242 - accuracy: 0.6659 - val_loss: 4.2336 - val_accuracy: 0.4397
Epoch 3/30
42/42 - 2s - loss: 2.4302 - accuracy: 0.8300 - val_loss: 3.6685 - val_accuracy: 0.5000
Epoch 4/30
42/42 - 2s - loss: 2.1704 - accuracy: 0.9150 - val_loss: 3.5941 - val_accuracy: 0.5379
Epoch 5/30
42/42 - 2s - loss: 2.0636 - accuracy: 0.9418 - val_loss: 3.5841 - val_accuracy: 0.5536
Epoch 6/30
42/42 - 2s - loss: 2.0220 - accuracy: 0.9493 - val_loss: 3.5650 - val_accuracy: 0.5469
Epoch 7/30
42/42 - 2s - loss: 1.9604 - accuracy: 0.9597 - val_loss: 3.5451 - val_accuracy: 0.5491
Epoch 8/30
42/42 - 2s - loss: 1.9010 - accuracy: 0.9843 - val_loss: 3.5753 - val_accuracy: 0.5848
Epoch 9/30
42/42 - 2s - loss: 1.8591 - accuracy: 0.9903 - val_loss: 3.6688 - val_accuracy: 0.5670
Epoch 10/30
42/42 - 2s - loss: 1.8443 - accuracy: 0.9925 - val_loss: 3.7009 - val_accuracy: 0.5737
Epoch 11/30
42/42 -

In [ ]:
'''Save the model weights into a h5 file'''
save_json = model.to_json()
with open('BirdDetectionDeep-4.json','w') as json_file:
    json_file.write(save_json )
model.save('BirdDetectionDeep-4.h5')